version: '2'

services:
  foros:
    # image: teamlinked2019/backend_foros:v2.7
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - /code:/var/lib/foros
    ports:
        - "8000:8000"
    depends_on:
        - db
        - migration
    labels:
        io.rancher.scheduler.global: 'true'
  migration: 
    #image: teamlinked2019/backend_foros:v2.7
    build: .
    command: bash -c "python manage.py makemigrations foros && python manage.py migrate"
    volumes:
      - /code:/var/lib/foros
    depends_on:
      - db
    restart: "no"
    labels:
      io.rancher.scheduler.global: 'true'
  db:
    image: mysql:5.7
    environment:
      DATABASE_HOST: db
      MYSQL_DATABASE: foros
      MYSQL_PASSWORD: password_123
      MYSQL_PORT: '3306'
      MYSQL_ROOT_PASSWORD: password_123
      MYSQL_USER: user
    ports:
      - 3307:3306
    labels:
      io.rancher.scheduler.global: 'true'
      
      