# Generated by Django 2.2.9 on 2020-01-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=50)),
                ('contenido', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(blank=True, default='', max_length=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('imagen', models.TextField(blank=True, default='', null=True)),
                ('id_creador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Creador_Foro', to='foros.Usuario')),
            ],
            options={
                'ordering': ('fecha_creacion', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, default='', null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('id_foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Foro_comentado', to='foros.Foro')),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Participante_Foro', to='foros.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionForo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categoria_Foro', to='foros.Categoria')),
                ('id_foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Foro_a_clasificar', to='foros.Foro')),
            ],
        ),
    ]
